### ISSUE TITLE
TLS support ?

### ISSUE THREAD

**Issue by gilou** [savonet/ocaml-cry#2]
Could liq stream using TLS to icecast since it does now support it, and (it seems, for 2.4.x at least) libshout as well?

**Comment by gilou** [comment]
OK, I'm dumb and haven't looked at this for a long time, ocaml-cry doesn't rely on libshout anymore. Feature request still stands, and since it won't be a "simple" parameter to set, I guess it'll be hard, depending how easily we can do TLS using ocaml...

**Comment by smimram** [comment]
We have developped [ocaml-ssl](https://github.com/savonet/ocaml-ssl) which supports TLS, so it should not be that difficult actually...

**Comment by toots** [comment]
Done!
